<$PLAN9/src/mkhdr

TARG=\
	tra\
	trafixdb\
	tramkdb\
	trasrv\
	trascan\
	tradump\
	trafixdb\

PROGS=${TARG:%=$O.%}

all:V: $PROGS

OFILES=\
	$SYSNAME.$O\
	atom.$O\
	avl.$O\
	banner.$O\
	clist.$O\
	clnt.$O\
	dat.$O\
	db.$O\
	fdbuf.$O\
	hash.$O\
	ignore.$O\
	list.$O\
	mux.$O\
	noconfig.$O\
	path.$O\
	qsort.$O\
	queue.$O\
	repl.$O\
	rpc.$O\
	srv.$O\
	stat.$O\
	storage.$O\
	strcache.$O\
	synckids.$O\
	syncfinish.$O\
	syncthread.$O\
	synctriage.$O\
	syncstat.$O\
	time.$O\
	unix.$O\
	util.$O\
	work.$O\

HFILES=tra.h

LIB=libtra.a
BIN=/usr/local/bin

<$PLAN9/src/mklib

CLEANFILES=$CLEANFILES $PROGS

all:V: $PROGS

install:V: $PROGS
	for i in $TARG
	do
		cp $O.$i $BIN/$i
	done

f5:V: install
	scp /usr/local/bin/tra* root@f5:/usr/local/bin

nuke:V: nuke-common 
	(cd libzlib ; mk nuke)

$O.%: %.$O $LIB libzlib/libzlib.a
	$LD $LDFLAGS -o $target $prereq

libzlib/libzlib.a:
	( cd libzlib ; mk )

$O.tradump $O.trafixdb: noclist.$O

test:V: $O.tramkdb $O.tra $O.trasrv $O.tradump
	TRASRV=./o.trasrv
	TRAMKDB=./o.tramkdb
	TRADUMP=./o.tradump
	TRASCAN=./o.trascan
	TRATMP=/tmp/tratest
	SYNC=./o.tra
	export TRASRV TRAMKDB TRADUMP TRASCAN TRATMP SYNC
	rc ../testfn.rc ../test/*


test.%:V: $O.tramkdb $O.tra $O.trasrv $O.tradump
	TRASRV=./o.trasrv
	TRAMKDB=./o.tramkdb
	TRADUMP=./o.tradump
	TRASCAN=./o.trascan
	TRATMP=/tmp/tratest
	SYNC=./o.tra
	export TRASRV TRAMKDB TRADUMP TRASCAN TRATMP SYNC
	rc ../testfn.rc ../test/$stem.*

